/*/g/libs/tiny-slider/2.9.2/js/tiny-slider.min.js*/
var tns=function(){function Mc(){for(var c,e,k,q=arguments[0]||{},w=1,M=arguments.length;w<M;w++)if(null!==(c=arguments[w]))for(e in c)k=c[e],q!==k&&void 0!==k&&(q[e]=k);return q}function ta(c){return 0<=["true","false"].indexOf(c)?JSON.parse(c):c}function ua(c,e,k,q){if(q)try{c.setItem(e,k)}catch(w){}return k}function ne(){var c=window.tnsId;window.tnsId=c?c+1:1;return"tns"+window.tnsId}function ec(){var c=document,e=c.body;e||(e=c.createElement("body"),e.fake=!0);return e}function fc(c){var e="";
c.fake&&(e=yb.style.overflow,c.style.background="",c.style.overflow=yb.style.overflow="hidden",yb.appendChild(c));return e}function gc(c,e){c.fake&&(c.remove(),yb.style.overflow=e,yb.offsetHeight)}function oe(){var c=document,e=ec(),k=fc(e);c=c.createElement("div");var q=!1;e.appendChild(c);try{for(var w=["calc(10px * 10)","-moz-calc(10px * 10)","-webkit-calc(10px * 10)"],M,va=0;3>va;va++)if(M=w[va],c.style.width=M,100===c.offsetWidth){q=M.replace("(10px * 10)","");break}}catch(zb){}e.fake?gc(e,k):
c.remove();return q}function pe(){var c=document,e=ec(),k=fc(e),q=c.createElement("div");c=c.createElement("div");var w="";q.className="tns-t-subp2";c.className="tns-t-ct";for(var M=0;70>M;M++)w+="<div></div>";c.innerHTML=w;q.appendChild(c);e.appendChild(q);c=2>Math.abs(q.getBoundingClientRect().left-c.children[67].getBoundingClientRect().left);e.fake?gc(e,k):q.remove();return c}function qe(){var c=document,e=ec(),k=fc(e),q=c.createElement("div"),w=c.createElement("style");w.type="text/css";q.className=
"tns-mq-test";e.appendChild(w);e.appendChild(q);w.styleSheet?w.styleSheet.cssText="@media all and (min-width:1px){.tns-mq-test{position:absolute}}":w.appendChild(c.createTextNode("@media all and (min-width:1px){.tns-mq-test{position:absolute}}"));c=window.getComputedStyle?window.getComputedStyle(q).position:q.currentStyle.position;e.fake?gc(e,k):q.remove();return"absolute"===c}function re(c){var e=document.createElement("style");c&&e.setAttribute("media",c);document.querySelector("head").appendChild(e);
return e.sheet?e.sheet:e.styleSheet}function Ia(c,e,k,q){"insertRule"in c?c.insertRule(e+"{"+k+"}",q):c.addRule(e,k,q)}function Ga(c){return("insertRule"in c?c.cssRules:c.rules).length}function Ja(c,e,k){for(var q=0,w=c.length;q<w;q++)e.call(k,c[q],q)}function ja(c,e){c="undefined"!==typeof c.item||c instanceof Array?c:[c];if("[object Object]"===Object.prototype.toString.call(e))for(var k=c.length;k--;)for(var q in e)c[k].setAttribute(q,e[q])}function Ka(c,e){c="undefined"!==typeof c.item||c instanceof
Array?c:[c];e=e instanceof Array?e:[e];for(var k=e.length,q=c.length;q--;)for(var w=k;w--;)c[q].removeAttribute(e[w])}function sd(c){for(var e=[],k=0,q=c.length;k<q;k++)e.push(c[k]);return e}function ka(c,e){"none"!==c.style.display&&(c.style.display="none")}function la(c,e){"none"===c.style.display&&(c.style.display="")}function Ab(c){if("string"===typeof c){var e=[c],k=c.charAt(0).toUpperCase()+c.substr(1);["Webkit","Moz","ms","O"].forEach(function(va){"ms"===va&&"transform"!==c||e.push(va+k)});
c=e}for(var q=document.createElement("fakeelement"),w=0;w<c.length;w++){var M=c[w];if(void 0!==q.style[M])return M}return!1}function se(c){if(!c||!window.getComputedStyle)return!1;var e=document,k=ec(),q=fc(k);e=e.createElement("p");var w=9<c.length?"-"+c.slice(0,-9).toLowerCase()+"-":"";w+="transform";k.insertBefore(e,null);e.style[c]="translate3d(1px,1px,1px)";c=window.getComputedStyle(e).getPropertyValue(w);k.fake?gc(k,q):e.remove();return void 0!==c&&0<c.length&&"none"!==c}function td(c,e){var k=
!1;/^Webkit/.test(c)?k="webkit"+e+"End":/^O/.test(c)?k="o"+e+"End":c&&(k=e.toLowerCase()+"end");return k}function K(c,e,k){for(var q in e){var w=0<=["touchstart","touchmove"].indexOf(q)&&!k?ud:!1;c.addEventListener(q,e[q],w)}}function T(c,e){for(var k in e){var q=0<=["touchstart","touchmove"].indexOf(k)?ud:!1;c.removeEventListener(k,e[k],q)}}function te(){return{topics:{},on:function(c,e){this.topics[c]=this.topics[c]||[];this.topics[c].push(e)},off:function(c,e){if(this.topics[c])for(var k=0;k<this.topics[c].length;k++)if(this.topics[c][k]===
e){this.topics[c].splice(k,1);break}},emit:function(c,e){e.type=c;this.topics[c]&&this.topics[c].forEach(function(k){k(e,c)})}}}function ue(c,e,k,q,w,M,va){function zb(){M-=La;kb+=wa;c.style[e]=k+kb+lb+q;0<M?setTimeout(zb,La):va()}var La=Math.min(M,10),lb=0<=w.indexOf("%")?"%":"px";w=w.replace(lb,"");var kb=Number(c.style[e].replace(k,"").replace(q,"").replace(lb,"")),wa=(w-kb)/M*La;setTimeout(zb,La)}var ya=window,Ma=ya.requestAnimationFrame||ya.webkitRequestAnimationFrame||ya.mozRequestAnimationFrame||
ya.msRequestAnimationFrame||function(c){return setTimeout(c,16)};ya=window;var Nc=ya.cancelAnimationFrame||ya.mozCancelAnimationFrame||function(c){clearTimeout(c)},yb=document.documentElement,mb=(ya="classList"in document.createElement("_"))?function(c,e){return c.classList.contains(e)}:function(c,e){return 0<=c.className.indexOf(e)},N=ya?function(c,e){mb(c,e)||c.classList.add(e)}:function(c,e){mb(c,e)||(c.className+=" "+e)},ea=ya?function(c,e){mb(c,e)&&c.classList.remove(e)}:function(c,e){mb(c,e)&&
(c.className=c.className.replace(e,""))},vd=!1;try{var ve=Object.defineProperty({},"passive",{get:function(){vd=!0}});window.addEventListener("test",null,ve)}catch(c){}var ud=vd?{passive:!0}:!1;"remove"in Element.prototype||(Element.prototype.remove=function(){this.parentNode&&this.parentNode.removeChild(this)});var me=function(c){function e(a){for(var b in a)n||("slideBy"===b&&(a[b]="page"),"edgePadding"===b&&(a[b]=!1),"autoHeight"===b&&(a[b]=!1)),"responsive"===b&&e(a[b])}function k(a){a&&(za=Aa=
Na=Oa=Pa=Z=Qa=Ra=!1)}function q(){for(var a=n?g-U:g;0>a;)a+=r;return a%r+1}function w(a){a=a?Math.max(0,Math.min(V?r-1:r-x,a)):0;return n?a+U:a}function M(a){null==a&&(a=g);for(n&&(a-=U);0>a;)a+=r;return Math.floor(a%r)}function va(){var a=M();a=Bb?a:p||u?Math.ceil((a+1)*pa/r-1):Math.floor(a/x);!V&&n&&g===ma&&(a=pa-1);return a}function zb(){if(u||p&&!Oc)var a=r-1;else{a=p?"fixedWidth":"items";var b=[];(p||c[a]<r)&&b.push(c[a]);if(F)for(var d in F){var f=F[d][a];f&&(p||f<r)&&b.push(f)}b.length||b.push(0);
a=Math.ceil(p?Oc/Math.min.apply(null,b):Math.max.apply(null,b))}b=n?Math.ceil((5*a-r)/2):4*a-r;b=Math.max(a,b);return wa("edgePadding")?b+1:b}function La(a){return"top"===a?"afterbegin":"beforeend"}function lb(a){if(null!=a){var b=Q.createElement("div");a.appendChild(b);var d=b.getBoundingClientRect();d=d.right-d.left;b.remove();return d||lb(a.parentNode)}}function kb(){var a=H?2*H-y:0;return lb(Pc)-a}function wa(a){if(c[a])return!0;if(F)for(var b in F)if(F[b][a])return!0;return!1}function t(a,b){null==
b&&(b=hc);if("items"===a&&p)return Math.floor((R+y)/(p+y))||1;var d=c[a];if(F)for(var f in F)b>=parseInt(f)&&a in F[f]&&(d=F[f][a]);"slideBy"===a&&"page"===d&&(d=t("items"));n||"slideBy"!==a&&"items"!==a||(d=Math.floor(d));return d}function ic(a,b,d,f,h){var l="";void 0!==a?(d=a,b&&(d-=b),l=B?"margin: 0 "+d+"px 0 "+a+"px;":"margin: "+a+"px 0 "+d+"px 0;"):b&&!d&&(a="-"+b+"px",l="margin: 0 "+(B?a+" 0 0":"0 "+a+" 0")+";");!n&&h&&L&&f&&(l+=$a(f));return l}function jc(a,b,d){return a?(a+b)*A+"px":ab?ab+
"("+100*A+"% / "+d+")":100*A/d+"%"}function kc(a,b,d){a?a=a+b+"px":(n||(d=Math.floor(d)),a=n?A:d,a=ab?ab+"(100% / "+a+")":100/a+"%");a="width:"+a;return"inner"!==nb?a+";":a+" !important;"}function lc(a){var b="";!1!==a&&(b=(B?"padding-":"margin-")+(B?"right":"bottom")+": "+a+"px;");return b}function wd(a,b){var d=a.substring(0,a.length-b).toLowerCase();d&&(d="-"+d+"-");return d}function $a(a){return wd(L,18)+"transition-duration:"+a/1E3+"s;"}function xd(a){return wd(mc,17)+"animation-duration:"+a/
1E3+"s;"}function yd(){if(wa("autoHeight")||u||!B){var a=m.querySelectorAll("img");Ja(a,function(b){var d=b.src;Cb||(d&&0>d.indexOf("data:image")?(b.src="",K(b,nc),N(b,"loading"),b.src=d):(N(b,"loaded"),oc(b)))});Ma(function(){pc(sd(a),function(){Qc=!0})});wa("autoHeight")&&(a=Rc(g,Math.min(g+x-1,A-1)));Cb?zd():Ma(function(){pc(sd(a),zd)})}else n&&Db(),Ad(),Bd()}function zd(){if(u){var a=V?g:r-1;(function d(){var f=z[a].getBoundingClientRect().left,h=z[a-1].getBoundingClientRect().right;1>=Math.abs(f-
h)?Cd():setTimeout(function(){d()},16)})()}else Cd()}function Cd(){if(!B||u)Dd(),u?(ob=Sc(),qc&&(qa=Tc()),ma=Eb(),k(fa||qa)):Uc();n&&Db();Ad();Bd()}function Ad(){Vc();da.insertAdjacentHTML("afterbegin",'<div class="tns-liveregion tns-visually-hidden" aria-live="polite" aria-atomic="true">slide <span class="current">'+Ed()+"</span>  of "+r+"</div>");Wc=da.querySelector(".tns-liveregion .current");if(Xc){var a=Z?"stop":"start";I?ja(I,{"data-action":a}):c.autoplayButtonOutput&&(da.insertAdjacentHTML(La(c.autoplayPosition),
'<button type="button" data-action="'+a+'">'+Fb[0]+a+Fb[1]+Sa[0]+"</button>"),I=da.querySelector("[data-action]"));I&&K(I,{click:Fd});Z&&(rc(),Qa&&K(m,Gb),Ra&&K(m,Hb))}if(Yc){if(W)ja(W,{"aria-label":"Carousel Pagination"}),na=W.children,Ja(na,function(f,h){ja(f,{"data-nav":h,tabindex:"-1","aria-label":pb+(h+1),"aria-controls":J})});else{a="";for(var b=Bb?"":'style="display:none"',d=0;d<r;d++)a+='<button type="button" data-nav="'+d+'" tabindex="-1" aria-controls="'+J+'" '+b+' aria-label="'+pb+(d+1)+
'"></button>';a='<div class="tns-nav" aria-label="Carousel Pagination">'+a+"</div>";da.insertAdjacentHTML(La(c.navPosition),a);W=da.querySelector(".tns-nav");na=W.children}Gd();L&&(a=L.substring(0,L.length-18).toLowerCase(),b="transition: all "+ra/1E3+"s",a&&(b="-"+a+"-"+b),Ia(C,"[aria-controls^="+J+"-item]",b,Ga(C)));ja(na[oa],{"aria-label":pb+(oa+1)+Zc});Ka(na[oa],"tabindex");N(na[oa],sc);K(W,$c)}if(tc){O||D&&E||(da.insertAdjacentHTML(La(c.controlsPosition),'<div class="tns-controls" aria-label="Carousel Navigation" tabindex="0"><button type="button" data-controls="prev" tabindex="-1" aria-controls="'+
J+'">'+Ta[0]+'</button><button type="button" data-controls="next" tabindex="-1" aria-controls="'+J+'">'+Ta[1]+"</button></div>"),O=da.querySelector(".tns-controls"));D&&E||(D=O.children[0],E=O.children[1]);c.controlsContainer&&ja(O,{"aria-label":"Carousel Navigation",tabindex:"0"});(c.controlsContainer||c.prevButton&&c.nextButton)&&ja([D,E],{"aria-controls":J,tabindex:"-1"});if(c.controlsContainer||c.prevButton&&c.nextButton)ja(D,{"data-controls":"prev"}),ja(E,{"data-controls":"next"});Ib="button"===
D.nodeName.toLowerCase();Jb="button"===E.nodeName.toLowerCase();Hd();O?K(O,Kb):(K(D,Kb),K(E,Kb))}ad()}function Bd(){if(n&&bb){var a={};a[bb]=Ba;K(m,a)}Na&&K(m,Lb,c.preventScrollOnTouch);Oa&&K(m,Mb);Pa&&K(Q,Nb);if("inner"===nb)S.on("outerResized",function(){Id();S.emit("innerLoaded",aa())});else(F||p||u||ha||!B)&&K(Ca,{resize:Jd});if(ha)if("outer"===nb)S.on("innerLoaded",uc);else fa||uc();bd();fa?Kd():qa&&Ld();S.on("indexChanged",Md);"inner"===nb&&S.emit("innerLoaded",aa());"function"===typeof cd&&
cd(aa());Ob=!0}function Jd(a){Ma(function(){Id(Ha(a))})}function Id(a){if(Ob){"outer"===nb&&S.emit("outerResized",aa(a));hc=Ca.innerWidth||Q.documentElement.clientWidth||Q.body.clientWidth;var b,d=Pb,f=!1;F&&(Nd(),(b=d!==Pb)&&S.emit("newBreakpointStart",aa(a)));var h,l=x,G=fa,cb=qa,db=Pa,dd=za,ed=Aa,qb=Na,fd=Oa,vc=Z,we=Qa,xe=Ra;d=g;if(b){var Qb=p,Rb=ha,wc=Ta,ye=X;var Sb=Sa;if(!rb)var Tb=y,xc=H}Pa=t("arrowKeys");za=t("controls");Aa=t("nav");Na=t("touch");X=t("center");Oa=t("mouseDrag");Z=t("autoplay");
Qa=t("autoplayHoverPause");Ra=t("autoplayResetOnVisibility");b&&(fa=t("disable"),p=t("fixedWidth"),ra=t("speed"),ha=t("autoHeight"),Ta=t("controlsText"),Sa=t("autoplayText"),gd=t("autoplayTimeout"),rb||(H=t("edgePadding"),y=t("gutter")));k(fa);R=kb();B&&!u||fa||(Dd(),B||(Uc(),f=!0));if(p||u)ob=Sc(),ma=Eb();if(b||p)if(x=t("items"),sb=t("slideBy"),h=x!==l)p||u||(ma=Eb()),hd();if(b&&fa!==G)if(fa)Kd();else if(Ub){C.disabled=!1;m.className+=Ua;Db();if(V)for(l=U;l--;)n&&la(z[l]),la(z[A-l-1]);if(!n)for(l=
g,G=g+r;l<G;l++){var Od=z[l],ze=l<g+x?Va:Da;Od.style.left=100*(l-g)/x+"%";N(Od,ze)}Pd();Ub=!1}if(qc&&(b||p||u)&&(qa=Tc(),qa!==cb))if(qa)id(yc(w(0))),Ld();else{if(Vb){H&&rb&&(ba.style.margin="");if(U)for(f=U;f--;)n&&ea(z[f],"tns-transparent"),ea(z[A-f-1],"tns-transparent");Pd();Vb=!1}f=!0}k(fa||qa);Z||(Qa=Ra=!1);Pa!==db&&(Pa?K(Q,Nb):T(Q,Nb));za!==dd&&(za?O?la(O):(D&&la(D),E&&la(E)):O?ka(O):(D&&ka(D),E&&ka(E)));Aa!==ed&&(Aa?la(W):ka(W));Na!==qb&&(Na?K(m,Lb,c.preventScrollOnTouch):T(m,Lb));Oa!==fd&&
(Oa?K(m,Mb):T(m,Mb));Z!==vc&&(Z?(I&&la(I),ia||tb||rc()):(I&&ka(I),ia&&Wb()));Qa!==we&&(Qa?K(m,Gb):T(m,Gb));Ra!==xe&&(Ra?K(Q,Hb):T(Q,Hb));if(b){if(p!==Qb||X!==ye)f=!0;ha===Rb||ha||(ba.style.height="");za&&Ta!==wc&&(D.innerHTML=Ta[0],E.innerHTML=Ta[1]);I&&Sa!==Sb&&(Qb=Z?1:0,Rb=I.innerHTML,wc=Rb.length-Sb[Qb].length,Rb.substring(wc)===Sb[Qb]&&(I.innerHTML=Rb.substring(0,wc)+Sa[Qb]))}else X&&(p||u)&&(f=!0);if(h||p&&!u)pa=Qd(),Gd();if(Sb=g!==d)S.emit("indexChanged",aa()),f=!0;else if(h)Sb||Md();else if(p||
u)bd(),Vc(),Rd();h&&!n&&Ae();if(!fa&&!qa){if(b&&!rb){if(H!==xc||y!==Tb)ba.style.cssText=ic(H,y,p,ra,ha);B&&(n&&(m.style.width=jc(p,y,x)),h=kc(p,y,x)+lc(y),Tb=C,xc=Ga(C)-1,"deleteRule"in Tb?Tb.deleteRule(xc):Tb.removeRule(xc),Ia(C,"#"+J+" > .tns-item",h,Ga(C)))}ha&&uc();f&&(Db(),Wa=g)}b&&S.emit("newBreakpointEnd",aa(a))}}function Tc(){if(!p&&!u)return r<=(X?x-(x-1)/2:x);var a=p?(p+y)*r:P[r],b=H?R+2*H:R+y;X&&(b-=p?(R-p)/2:(R-(P[g+1]-P[g]-y))/2);return a<=b}function Nd(){Pb=0;for(var a in F)a=parseInt(a),
hc>=a&&(Pb=a)}function ad(){!Z&&I&&ka(I);!Aa&&W&&ka(W);za||(O?ka(O):(D&&ka(D),E&&ka(E)))}function Pd(){Z&&I&&la(I);Aa&&W&&la(W);za&&(O?la(O):(D&&la(D),E&&la(E)))}function Ld(){if(!Vb){H&&(ba.style.margin="0px");if(U)for(var a=U;a--;)n&&N(z[a],"tns-transparent"),N(z[A-a-1],"tns-transparent");ad();Vb=!0}}function Kd(){if(!Ub){C.disabled=!0;m.className=m.className.replace(Ua.substring(1),"");Ka(m,["style"]);if(V)for(var a=U;a--;)n&&ka(z[a]),ka(z[A-a-1]);B&&n||Ka(ba,["style"]);if(!n){a=g;for(var b=g+
r;a<b;a++){var d=z[a];Ka(d,["style"]);ea(d,Va);ea(d,Da)}}ad();Ub=!0}}function Rd(){var a=Ed();Wc.innerHTML!==a&&(Wc.innerHTML=a)}function Ed(){var a=zc(),b=a[0]+1;a=a[1]+1;return b===a?b+"":b+" to "+a}function zc(a){null==a&&(a=yc());var b=g;if(X||H){if(u||p){var d=-(parseFloat(a)+H);var f=d+R+2*H}}else u&&(d=P[g],f=d+R);if(u)P.forEach(function(l,G){G<A&&((X||H)&&l<=d+.5&&(b=G),.5<=f-l&&(h=G))});else{if(p)if(a=p+y,X||H){b=Math.floor(d/a);var h=Math.ceil(f/a-1)}else h=b+Math.ceil(R/a)-1;else X||H?
(a=x-1,X?(b-=a/2,h=g+a/2):h=g+a,H&&(a=H*x/R,b-=a,h+=a),b=Math.floor(b),h=Math.ceil(h)):h=b+x-1;b=Math.max(b,0);h=Math.min(h,A-1)}return[b,h]}function bd(){if(Cb&&!fa){var a=zc();a.push(Be);Rc.apply(null,a).forEach(function(b){if(!mb(b,Ac)){var d={};d[bb]=function(f){f.stopPropagation()};K(b,d);K(b,nc);b.src=b.getAttribute("data-src");if(d=b.getAttribute("data-srcset"))b.srcset=d;N(b,"loading")}})}}function oc(a){N(a,Ac);ea(a,"loading");T(a,nc)}function Rc(a,b,d){var f=[];for(d||(d="img");a<=b;)Ja(z[a].querySelectorAll(d),
function(h){f.push(h)}),a++;return f}function uc(){var a=Rc.apply(null,zc());Ma(function(){pc(a,Sd)})}function pc(a,b){if(Qc)return b();a.forEach(function(d,f){!Cb&&d.complete&&oc(d);mb(d,Ac)&&a.splice(f,1)});if(!a.length)return b();Ma(function(){pc(a,b)})}function Md(){bd();Vc();Rd();Hd();if(Aa&&(oa=0<=eb?eb:va(),eb=-1,oa!==ub)){var a=na[ub],b=na[oa];ja(a,{tabindex:"-1","aria-label":pb+(ub+1)});ea(a,sc);ja(b,{"aria-label":pb+(oa+1)+Zc});Ka(b,"tabindex");N(b,sc);ub=oa}}function Td(a,b){for(var d=
[],f=a,h=Math.min(a+b,A);f<h;f++)d.push(z[f].offsetHeight);return Math.max.apply(null,d)}function Sd(){var a=ha?Td(g,x):Td(U,r),b=ca?ca:ba;b.style.height!==a&&(b.style.height=a+"px")}function Dd(){P=[0];var a=B?"left":"top",b=B?"right":"bottom",d=z[0].getBoundingClientRect()[a];Ja(z,function(f,h){h&&P.push(f.getBoundingClientRect()[a]-d);h===A-1&&P.push(f.getBoundingClientRect()[b]-d)})}function Vc(){var a=zc(),b=a[0],d=a[1];Ja(z,function(f,h){h>=b&&h<=d?f.hasAttribute("aria-hidden")&&(Ka(f,["aria-hidden",
"tabindex"]),N(f,jd)):f.hasAttribute("aria-hidden")||(ja(f,{"aria-hidden":"true",tabindex:"-1"}),ea(f,jd))})}function Ae(){for(var a=g+Math.min(r,x),b=A;b--;){var d=z[b];b>=g&&b<a?(N(d,"tns-moving"),d.style.left=100*(b-g)/x+"%",N(d,Va),ea(d,Da)):d.style.left&&(d.style.left="",N(d,Da),ea(d,Va));ea(d,Bc)}setTimeout(function(){Ja(z,function(f){ea(f,"tns-moving")})},300)}function Cc(a,b,d){a?b.disabled=d:b.setAttribute("aria-disabled",d.toString())}function Hd(){if(za&&!Xb&&!V){var a=Ib?D.disabled:"true"===
D.getAttribute("aria-disabled"),b=Jb?E.disabled:"true"===E.getAttribute("aria-disabled"),d=g<=Ea?!0:!1,f=!Xb&&g>=ma?!0:!1;d&&!a&&Cc(Ib,D,!0);!d&&a&&Cc(Ib,D,!1);f&&!b&&Cc(Jb,E,!0);!f&&b&&Cc(Jb,E,!1)}}function Yb(a){null==a&&(a=g);var b=H?y:0;return u?(R-b-(P[a+1]-P[a]-y))/2:p?(R-p)/2:(x-1)/2}function Sc(){var a=R+(H?y:0)-(p?(p+y)*A:P[A]);X&&!V&&(a=p?-(p+y)*(A-1)-Yb():Yb(A-1)-P[A-1]);0<a&&(a=0);return a}function yc(a){null==a&&(a=g);if(B&&!u)if(p)a*=-(p+y),X&&(a+=Yb());else{var b=Zb?A:x;X&&(a-=Yb());
a=100*-a/b}else a=-P[a],X&&u&&(a+=Yb());Ud&&(a=Math.max(a,ob));return a+=!B||u||p?"px":"%"}function Db(a){L&&(m.style[L]="0s");id(a)}function id(a){null==a&&(a=yc());m.style[fb]=Xa+a+vb}function Vd(a,b,d,f){var h=a+x;V||(h=Math.min(h,A));for(var l=a;l<h;l++){var G=z[l];f||(G.style.left=100*(l-g)/x+"%");kd&&Dc&&(G.style[Dc]=G.style[ld]=kd*(l-a)/1E3+"s");ea(G,b);N(G,d);f&&wb.push(G)}}function md(a,b){nd&&hd();if(g!==Wa||b)S.emit("indexChanged",aa()),S.emit("transitionStart",aa()),ha&&uc(),ia&&a&&0<=
["click","keydown"].indexOf(a.type)&&Wb(),Ya=!0,Ce()}function Ba(a){if(n||Ya){S.emit("transitionEnd",aa(a));if(!n&&0<wb.length)for(var b=0;b<wb.length;b++){var d=wb[b];d.style.left="";ld&&Dc&&(d.style[ld]="",d.style[Dc]="");ea(d,Bc);N(d,Da)}if(!a||!n&&a.target.parentNode===m||a.target===m&&a.propertyName.toLowerCase().replace(/-/g,"")===fb.toLowerCase().replace(/-/g,""))nd||(a=g,hd(),g!==a&&(S.emit("indexChanged",aa()),Db())),"inner"===nb&&S.emit("innerLoaded",aa()),Ya=!1,Wa=g}}function $b(a,b){if(!qa)if("prev"===
a)Za(b,-1);else if("next"===a)Za(b,1);else{if(Ya){if(Ec)return;Ba()}var d=M(),f=0;"first"===a?f=-d:"last"===a?f=n?r-x-d:r-1-d:("number"!==typeof a&&(a=parseInt(a)),isNaN(a)||(b||(a=Math.max(0,Math.min(r-1,a))),f=a-d));!n&&f&&Math.abs(f)<x&&(d=0<f?1:-1,f+=g+f-r>=Ea?r*d:2*r*d*-1);g+=f;n&&V&&(g<Ea&&(g+=r),g>ma&&(g-=r));M(g)!==M(Wa)&&md(b)}}function Za(a,b){if(Ya){if(Ec)return;Ba()}if(!b){a=Ha(a);for(var d=xb(a);d!==O&&0>[D,E].indexOf(d);)d=d.parentNode;d=[D,E].indexOf(d);if(0<=d){var f=!0;b=0===d?-1:
1}}if(Xb){if(g===Ea&&-1===b){$b("last",a);return}if(g===ma&&1===b){$b("first",a);return}}b&&(g+=sb*b,u&&(g=Math.floor(g)),md(f||a&&"keydown"===a.type?a:null))}function Fc(){Gc=setInterval(function(){Za(null,Wd)},gd);ia=!0}function Hc(){clearInterval(Gc);ia=!1}function Xd(a,b){ja(I,{"data-action":a});I.innerHTML=Fb[0]+a+Fb[1]+b}function rc(){Fc();I&&Xd("stop",Sa[1])}function Wb(){Hc();I&&Xd("start",Sa[0])}function Fd(){ia?(Wb(),tb=!0):(rc(),tb=!1)}function Ha(a){a=a||Ca.event;return gb(a)?a.changedTouches[0]:
a}function xb(a){return a.target||Ca.event.srcElement}function gb(a){return 0<=a.type.indexOf("touch")}function Yd(){var a=!1,b=Math.abs(90-Math.abs(180/Math.PI*Math.atan2(xa.y-hb.y,xa.x-hb.x)));b>=90-ac?a="horizontal":b<=ac&&(a="vertical");return a===c.axis}function Zd(a){if(Ya){if(Ec)return;Ba()}Z&&ia&&Hc();ib=!0;sa&&(Nc(sa),sa=null);var b=Ha(a);S.emit(gb(a)?"touchStart":"dragStart",aa(a));!gb(a)&&0<=["img","a"].indexOf(xb(a).nodeName.toLowerCase())&&(a.preventDefault?a.preventDefault():a.returnValue=
!1);xa.x=hb.x=b.clientX;xa.y=hb.y=b.clientY;n&&(Ic=parseFloat(m.style[fb].replace(Xa,"")),L&&(m.style[L]="0s"))}function $d(a){if(ib){var b=Ha(a);xa.x=b.clientX;xa.y=b.clientY;n?sa||(sa=Ma(function(){ae(a)})):("?"===Fa&&(Fa=Yd()),Fa&&(bc=!0));("boolean"!==typeof a.cancelable||a.cancelable)&&bc&&a.preventDefault()}}function ae(a){if(Fa){if(Nc(sa),ib&&(sa=Ma(function(){ae(a)})),"?"===Fa&&(Fa=Yd()),Fa){!bc&&gb(a)&&(bc=!0);try{a.type&&S.emit(gb(a)?"touchMove":"dragMove",aa(a))}catch(f){}var b=Ic,d=od(xa,
hb);!B||p||u?b=b+d+"px":(b+=Zb?d*x*100/((R+y)*A):100*d/(R+y),b+="%");m.style[fb]=Xa+b+vb}}else ib=!1}function Jc(a){if(ib){sa&&(Nc(sa),sa=null);n&&L&&(m.style[L]="");ib=!1;var b=Ha(a);xa.x=b.clientX;xa.y=b.clientY;var d=od(xa,hb);if(Math.abs(d)){if(!gb(a)){var f=xb(a);K(f,{click:function G(l){l.preventDefault?l.preventDefault():l.returnValue=!1;T(f,{click:G})}})}n?sa=Ma(function(){if(B&&!u){var h=-d*x/(R+y);h=0<d?Math.floor(h):Math.ceil(h);g+=h}else if(h=-(Ic+d),0>=h)g=Ea;else if(h>=P[A-1])g=ma;else for(var l=
0;l<A&&h>=P[l];)g=l,h>P[l]&&0>d&&(g+=1),l++;md(a,d);S.emit(gb(a)?"touchEnd":"dragEnd",aa(a))}):Fa&&Za(a,0<d?-1:1)}}"auto"===c.preventScrollOnTouch&&(bc=!1);ac&&(Fa="?");Z&&!ia&&Fc()}function Uc(){(ca?ca:ba).style.height=P[g+x]-P[g]+"px"}function Qd(){return Math.min(Math.ceil(p?(p+y)*r/R:r/x),r)}function Gd(){if(Aa&&!Bb&&pa!==jb){var a=jb,b=pa,d=la;jb>pa&&(a=pa,b=jb,d=ka);for(;a<b;)d(na[a]),a++;jb=pa}}function aa(a){return{container:m,slideItems:z,navContainer:W,navItems:na,controlsContainer:O,hasControls:tc,
prevButton:D,nextButton:E,items:x,slideBy:sb,cloneCount:U,slideCount:r,slideCountNew:A,index:g,indexCached:Wa,displayIndex:q(),navCurrentIndex:oa,navCurrentIndexCached:ub,pages:pa,pagesCached:jb,sheet:C,isOn:Ob,event:a||{}}}c=Mc({container:".slider",mode:"carousel",axis:"horizontal",items:1,gutter:0,edgePadding:0,fixedWidth:!1,autoWidth:!1,viewportMax:!1,slideBy:1,center:!1,controls:!0,controlsPosition:"top",controlsText:["prev","next"],controlsContainer:!1,prevButton:!1,nextButton:!1,nav:!0,navPosition:"top",
navContainer:!1,navAsThumbnails:!1,arrowKeys:!1,speed:300,autoplay:!1,autoplayPosition:"top",autoplayTimeout:5E3,autoplayDirection:"forward",autoplayText:["start","stop"],autoplayHoverPause:!1,autoplayButton:!1,autoplayButtonOutput:!0,autoplayResetOnVisibility:!0,animateIn:"tns-fadeIn",animateOut:"tns-fadeOut",animateNormal:"tns-normal",animateDelay:!1,loop:!0,rewind:!1,autoHeight:!1,responsive:!1,lazyload:!1,lazyloadSelector:".tns-lazy-img",touch:!0,mouseDrag:!1,swipeAngle:15,nested:!1,preventActionWhenRunning:!1,
preventScrollOnTouch:!1,freezable:!0,onInit:!1,useLocalStorage:!0},c||{});var Q=document,Ca=window,v={},Y=c.useLocalStorage;if(Y){var be=navigator.userAgent,cc=new Date;try{(v=Ca.localStorage)?(v.setItem(cc,cc),Y=v.getItem(cc)==cc,v.removeItem(cc)):Y=!1,Y||(v={})}catch(a){Y=!1}Y&&(v.tnsApp&&v.tnsApp!==be&&"tC tPL tMQ tTf t3D tTDu tTDe tADu tADe tTE tAE".split(" ").forEach(function(a){v.removeItem(a)}),localStorage.tnsApp=be)}var ab=v.tC?ta(v.tC):ua(v,"tC",oe(),Y),ce=v.tPL?ta(v.tPL):ua(v,"tPL",pe(),
Y),rb=v.tMQ?ta(v.tMQ):ua(v,"tMQ",qe(),Y),Zb=v.tTf?ta(v.tTf):ua(v,"tTf",Ab("transform"),Y),De=v.t3D?ta(v.t3D):ua(v,"t3D",se(Zb),Y),L=v.tTDu?ta(v.tTDu):ua(v,"tTDu",Ab("transitionDuration"),Y),Dc=v.tTDe?ta(v.tTDe):ua(v,"tTDe",Ab("transitionDelay"),Y),mc=v.tADu?ta(v.tADu):ua(v,"tADu",Ab("animationDuration"),Y),ld=v.tADe?ta(v.tADe):ua(v,"tADe",Ab("animationDelay"),Y),bb=v.tTE?ta(v.tTE):ua(v,"tTE",td(L,"Transition"),Y),de=v.tAE?ta(v.tAE):ua(v,"tAE",td(mc,"Animation"),Y),ee=Ca.console&&"function"===typeof Ca.console.warn,
pd="container controlsContainer prevButton nextButton navContainer autoplayButton".split(" "),fe={};pd.forEach(function(a){if("string"===typeof c[a]){var b=c[a],d=Q.querySelector(b);fe[a]=b;d&&d.nodeName?c[a]=d:ee&&console.warn("Can't find",c[a])}});if(1>c.container.children.length)ee&&console.warn("No slides found in",c.container);else{var F=c.responsive,nb=c.nested,n="carousel"===c.mode?!0:!1;if(F){0 in F&&(c=Mc(c,F[0]),delete F[0]);var qd={},rd;for(rd in F){var dc=F[rd];dc="number"===typeof dc?
{items:dc}:dc;qd[rd]=dc}F=qd;qd=null}n||e(c);if(!n){c.axis="horizontal";c.slideBy="page";c.edgePadding=!1;var Va=c.animateIn,Bc=c.animateOut,kd=c.animateDelay,Da=c.animateNormal}var B="horizontal"===c.axis?!0:!1,da=Q.createElement("div"),ba=Q.createElement("div"),ca,m=c.container,Pc=m.parentNode,ge=m.outerHTML,z=m.children,r=z.length,Pb,hc=Ca.innerWidth||Q.documentElement.clientWidth||Q.body.clientWidth,Ob=!1;F&&Nd();n&&(m.className+=" tns-vpfix");var u=c.autoWidth,p=t("fixedWidth"),H=t("edgePadding"),
y=t("gutter"),R=kb(),X=t("center"),x=u?1:Math.floor(t("items")),sb=t("slideBy"),Oc=c.viewportMax||c.fixedWidthViewportWidth,Pa=t("arrowKeys"),ra=t("speed"),Xb=c.rewind,V=Xb?!1:c.loop,ha=t("autoHeight"),za=t("controls"),Ta=t("controlsText"),Aa=t("nav"),Na=t("touch"),Oa=t("mouseDrag"),Z=t("autoplay"),gd=t("autoplayTimeout"),Sa=t("autoplayText"),Qa=t("autoplayHoverPause"),Ra=t("autoplayResetOnVisibility"),C=re(),Cb=c.lazyload,Be=c.lazyloadSelector,P,wb=[],U=V?zb():0,A=n?r+2*U:r+U,Ud=!p&&!u||V?!1:!0,
ob=p?Sc():null,nd=n&&V?!1:!0,fb=B?"left":"top",Xa="",vb="",Eb=function(){return p?function(){return X&&!V?r-1:Math.ceil(-ob/(p+y))}:u?function(){for(var a=A;a--;)if(P[a]>=-ob)return a}:function(){return X&&n&&!V?r-1:V||n?Math.max(0,A-Math.ceil(x)):A-1}}(),g=w(t("startIndex")),Wa=g;q();var Ea=0,ma=u?null:Eb(),Ec=c.preventActionWhenRunning,ac=c.swipeAngle,Fa=ac?"?":!0,Ya=!1,cd=c.onInit,S=new te,Ua=" tns-slider tns-"+c.mode,J=m.id||ne(),fa=t("disable"),Ub=!1,qc=c.freezable,qa=qc&&!u?Tc():!1,Vb=!1,Kb=
{click:Za,keydown:function(a){a=Ha(a);var b=[37,39].indexOf(a.keyCode);0<=b&&(0===b?D.disabled||Za(a,-1):E.disabled||Za(a,1))}},$c={click:function(a){if(Ya){if(Ec)return;Ba()}a=Ha(a);for(var b=xb(a);b!==W&&!b.hasAttribute("data-nav");)b=b.parentNode;if(b.hasAttribute("data-nav")){b=eb=Number(b.getAttribute("data-nav"));var d=p||u?b*r/pa:b*x;$b(Bb?b:Math.min(Math.ceil(d),r-1),a);oa===b&&(ia&&Wb(),eb=-1)}},keydown:function(a){a=Ha(a);var b=Q.activeElement;if(b.hasAttribute("data-nav")){var d=[37,39,
13,32].indexOf(a.keyCode);b=Number(b.getAttribute("data-nav"));0<=d&&(0===d?0<b&&na[b-1].focus():1===d?b<pa-1&&na[b+1].focus():(eb=b,$b(b,a)))}}},Gb={mouseover:function(){ia&&(Hc(),Kc=!0)},mouseout:function(){Kc&&(Fc(),Kc=!1)}},Hb={visibilitychange:function(){Q.hidden?ia&&(Hc(),Lc=!0):Lc&&(Fc(),Lc=!1)}},Nb={keydown:function(a){a=Ha(a);var b=[37,39].indexOf(a.keyCode);0<=b&&Za(a,0===b?-1:1)}},Lb={touchstart:Zd,touchmove:$d,touchend:Jc,touchcancel:Jc},Mb={mousedown:Zd,mousemove:$d,mouseup:Jc,mouseleave:Jc},
tc=wa("controls"),Yc=wa("nav"),Bb=u?!0:c.navAsThumbnails,Xc=wa("autoplay"),he=wa("touch"),ie=wa("mouseDrag"),jd="tns-slide-active",Ac="tns-complete",nc={load:function(a){a=xb(a);N(a,"loaded");oc(a)},error:function(a){a=xb(a);N(a,"failed");oc(a)}},Qc,Wc,bc="force"===c.preventScrollOnTouch?!0:!1;if(tc)var O=c.controlsContainer,je=c.controlsContainer?c.controlsContainer.outerHTML:"",D=c.prevButton,E=c.nextButton,Ee=c.prevButton?c.prevButton.outerHTML:"",Fe=c.nextButton?c.nextButton.outerHTML:"",Ib,Jb;
if(Yc)var W=c.navContainer,ke=c.navContainer?c.navContainer.outerHTML:"",na,pa=u?r:Qd(),jb=0,eb=-1,oa=va(),ub=oa,sc="tns-nav-active",pb="Carousel Page ",Zc=" (Current Slide)";if(Xc)var Wd="forward"===c.autoplayDirection?1:-1,I=c.autoplayButton,le=c.autoplayButton?c.autoplayButton.outerHTML:"",Fb=["<span class='tns-visually-hidden'>"," animation</span>"],Gc,ia,Kc,tb,Lc;if(he||ie)var hb={},xa={},Ic,ib=!1,sa,od=B?function(a,b){return a.x-b.x}:function(a,b){return a.y-b.y};u||k(fa||qa);Zb&&(fb=Zb,Xa=
"translate",De?(Xa+=B?"3d(":"3d(0px, ",vb=B?", 0px, 0px)":", 0px)"):(Xa+=B?"X(":"Y(",vb=")"));n&&(m.className=m.className.replace("tns-vpfix",""));(function(){wa("gutter");da.className="tns-outer";ba.className="tns-inner";da.id=J+"-ow";ba.id=J+"-iw";""===m.id&&(m.id=J);Ua+=ce||u?" tns-subpixel":" tns-no-subpixel";Ua+=ab?" tns-calc":" tns-no-calc";u&&(Ua+=" tns-autowidth");Ua+=" tns-"+c.axis;m.className+=Ua;n?(ca=Q.createElement("div"),ca.id=J+"-mw",ca.className="tns-ovh",da.appendChild(ca),ca.appendChild(ba)):
da.appendChild(ba);ha&&((ca?ca:ba).className+=" tns-ah");Pc.insertBefore(da,m);ba.appendChild(m);Ja(z,function(l,G){N(l,"tns-item");l.id||(l.id=J+"-item"+G);!n&&Da&&N(l,Da);ja(l,{"aria-hidden":"true",tabindex:"-1"})});if(U){for(var a=Q.createDocumentFragment(),b=Q.createDocumentFragment(),d=U;d--;){var f=d%r,h=z[f].cloneNode(!0);Ka(h,"id");b.insertBefore(h,b.firstChild);n&&(f=z[r-1-f].cloneNode(!0),Ka(f,"id"),a.appendChild(f))}m.insertBefore(a,m.firstChild);m.appendChild(b);z=m.children}})();(function(){if(!n)for(var a=
g,b=g+Math.min(r,x);a<b;a++){var d=z[a];d.style.left=100*(a-g)/x+"%";N(d,Va);ea(d,Da)}B&&(ce||u?(Ia(C,"#"+J+" > .tns-item","font-size:"+Ca.getComputedStyle(z[0]).fontSize+";",Ga(C)),Ia(C,"#"+J,"font-size:0;",Ga(C))):n&&Ja(z,function(fd,vc){fd.style.marginLeft=ab?ab+"("+100*vc+"% / "+A+")":100*vc/A+"%"}));rb?(L&&(b=ca&&c.autoHeight?$a(c.speed):"",Ia(C,"#"+J+"-mw",b,Ga(C))),b=ic(c.edgePadding,c.gutter,c.fixedWidth,c.speed,c.autoHeight),Ia(C,"#"+J+"-iw",b,Ga(C)),n&&(b=B&&!u?"width:"+jc(c.fixedWidth,
c.gutter,c.items)+";":"",L&&(b+=$a(ra)),Ia(C,"#"+J,b,Ga(C))),b=B&&!u?kc(c.fixedWidth,c.gutter,c.items):"",c.gutter&&(b+=lc(c.gutter)),n||(L&&(b+=$a(ra)),mc&&(b+=xd(ra)))):(n&&ha&&(ca.style[L]=ra/1E3+"s"),ba.style.cssText=ic(H,y,p,ha),n&&B&&!u&&(m.style.width=jc(p,y,x)),b=B&&!u?kc(p,y,x):"",y&&(b+=lc(y)));b&&Ia(C,"#"+J+" > .tns-item",b,Ga(C));if(F&&rb)for(var f in F){f=parseInt(f);a=F[f];var h=d=b=b="",l="",G=u?null:t("items",f),cb=t("fixedWidth",f),db=t("speed",f),dd=t("edgePadding",f),ed=t("autoHeight",
f),qb=t("gutter",f);L&&ca&&t("autoHeight",f)&&"speed"in a&&(b="#"+J+"-mw{"+$a(db)+"}");if("edgePadding"in a||"gutter"in a)d="#"+J+"-iw{"+ic(dd,qb,cb,db,ed)+"}";n&&B&&!u&&("fixedWidth"in a||"items"in a||p&&"gutter"in a)&&(h="width:"+jc(cb,qb,G)+";");L&&"speed"in a&&(h+=$a(db));h&&(h="#"+J+"{"+h+"}");if("fixedWidth"in a||p&&"gutter"in a||!n&&"items"in a)l+=kc(cb,qb,G);"gutter"in a&&(l+=lc(qb));!n&&"speed"in a&&(L&&(l+=$a(db)),mc&&(l+=xd(db)));l&&(l="#"+J+" > .tns-item{"+l+"}");(b=b+d+h+l)&&C.insertRule("@media (min-width: "+
f/16+"em) {"+b+"}",C.cssRules.length)}})();yd();var hd=function(){return V?n?function(){var a=Ea,b=ma;a+=sb;b-=sb;H?(a+=1,--b):p&&(R+y)%(p+y)&&--b;U&&(g>b?g-=r:g<a&&(g+=r))}:function(){if(g>ma)for(;g>=Ea+r;)g-=r;else if(g<Ea)for(;g<=ma-r;)g+=r}:function(){g=Math.max(Ea,Math.min(ma,g))}}(),Ce=function(){return n?function(){L&&(m.style[L]="");L||!ra?(id(),ra&&"none"!==window.getComputedStyle(m).display||Ba()):ue(m,fb,Xa,vb,yc(),ra,Ba);B||Uc()}:function(){wb=[];var a={};a[bb]=a[de]=Ba;T(z[Wa],a);K(z[g],
a);Vd(Wa,Va,Bc,!0);Vd(g,Da,Va);bb&&de&&ra&&"none"!==window.getComputedStyle(m).display||Ba()}}();return{version:"2.9.2",getInfo:aa,events:S,goTo:$b,play:function(){Z&&!ia&&(rc(),tb=!1)},pause:function(){ia&&(Wb(),tb=!0)},isOn:Ob,updateSliderHeight:Sd,refresh:yd,destroy:function(){C.disabled=!0;C.ownerNode&&C.ownerNode.remove();T(Ca,{resize:Jd});Pa&&T(Q,Nb);O&&T(O,Kb);W&&T(W,$c);T(m,Gb);T(m,Hb);I&&T(I,{click:Fd});Z&&clearInterval(Gc);if(n&&bb){var a={};a[bb]=Ba;T(m,a)}Na&&T(m,Lb);Oa&&T(m,Mb);var b=
[ge,je,Ee,Fe,ke,le];pd.forEach(function(f,h){var l="container"===f?da:c[f];if("object"===typeof l&&l){var G=l.previousElementSibling?l.previousElementSibling:!1,cb=l.parentNode;l.outerHTML=b[h];c[f]=G?G.nextElementSibling:cb.firstElementChild}});pd=Va=Bc=kd=Da=B=da=ba=m=Pc=ge=z=r=Pb=hc=u=p=H=y=R=x=sb=Oc=Pa=ra=Xb=V=ha=C=Cb=P=wb=U=A=Ud=ob=nd=fb=Xa=vb=Eb=g=Wa=Ea=ma=ac=Fa=Ya=cd=S=Ua=J=fa=Ub=qc=qa=Vb=Kb=$c=Gb=Hb=Nb=Lb=Mb=tc=Yc=Bb=Xc=he=ie=jd=Ac=nc=Qc=za=Ta=O=je=D=E=Ib=Jb=Aa=W=ke=na=pa=jb=eb=oa=ub=sc=pb=
Zc=Z=gd=Wd=Sa=Qa=I=le=Ra=Fb=Gc=ia=Kc=tb=Lc=hb=xa=Ic=ib=sa=od=Na=Oa=null;for(var d in this)"rebuild"!==d&&(this[d]=null);Ob=!1},rebuild:function(){return me(Mc(c,fe))}}}};return me}();
/*/g/libs/tiny-slider/2.9.2/js/tiny-slider.min.js*/


/*/g/libs/jquery-match-height/0.7.2/jquery.matchHeight.min.js*/
!function(t){"use strict";"function"==typeof define&&define.amd?define(["jquery"],t):"undefined"!=typeof module&&module.exports?module.exports=t(require("jquery")):t(jQuery)}(function(t){var e=-1,o=-1,n=function(t){return parseFloat(t)||0},a=function(e){var o=1,a=t(e),i=null,r=[];return a.each(function(){var e=t(this),a=e.offset().top-n(e.css("margin-top")),s=r.length>0?r[r.length-1]:null;null===s?r.push(e):Math.floor(Math.abs(i-a))<=o?r[r.length-1]=s.add(e):r.push(e),i=a}),r},i=function(e){var o={
    byRow:!0,property:"height",target:null,remove:!1};return"object"==typeof e?t.extend(o,e):("boolean"==typeof e?o.byRow=e:"remove"===e&&(o.remove=!0),o)},r=t.fn.matchHeight=function(e){var o=i(e);if(o.remove){var n=this;return this.css(o.property,""),t.each(r._groups,function(t,e){e.elements=e.elements.not(n)}),this}return this.length<=1&&!o.target?this:(r._groups.push({elements:this,options:o}),r._apply(this,o),this)};r.version="0.7.2",r._groups=[],r._throttle=80,r._maintainScroll=!1,r._beforeUpdate=null,
    r._afterUpdate=null,r._rows=a,r._parse=n,r._parseOptions=i,r._apply=function(e,o){var s=i(o),h=t(e),l=[h],c=t(window).scrollTop(),p=t("html").outerHeight(!0),u=h.parents().filter(":hidden");return u.each(function(){var e=t(this);e.data("style-cache",e.attr("style"))}),u.css("display","block"),s.byRow&&!s.target&&(h.each(function(){var e=t(this),o=e.css("display");"inline-block"!==o&&"flex"!==o&&"inline-flex"!==o&&(o="block"),e.data("style-cache",e.attr("style")),e.css({display:o,"padding-top":"0",
    "padding-bottom":"0","margin-top":"0","margin-bottom":"0","border-top-width":"0","border-bottom-width":"0",height:"100px",overflow:"hidden"})}),l=a(h),h.each(function(){var e=t(this);e.attr("style",e.data("style-cache")||"")})),t.each(l,function(e,o){var a=t(o),i=0;if(s.target)i=s.target.outerHeight(!1);else{if(s.byRow&&a.length<=1)return void a.css(s.property,"");a.each(function(){var e=t(this),o=e.attr("style"),n=e.css("display");"inline-block"!==n&&"flex"!==n&&"inline-flex"!==n&&(n="block");var a={
    display:n};a[s.property]="",e.css(a),e.outerHeight(!1)>i&&(i=e.outerHeight(!1)),o?e.attr("style",o):e.css("display","")})}a.each(function(){var e=t(this),o=0;s.target&&e.is(s.target)||("border-box"!==e.css("box-sizing")&&(o+=n(e.css("border-top-width"))+n(e.css("border-bottom-width")),o+=n(e.css("padding-top"))+n(e.css("padding-bottom"))),e.css(s.property,i-o+"px"))})}),u.each(function(){var e=t(this);e.attr("style",e.data("style-cache")||null)}),r._maintainScroll&&t(window).scrollTop(c/p*t("html").outerHeight(!0)),
    this},r._applyDataApi=function(){var e={};t("[data-match-height], [data-mh]").each(function(){var o=t(this),n=o.attr("data-mh")||o.attr("data-match-height");n in e?e[n]=e[n].add(o):e[n]=o}),t.each(e,function(){this.matchHeight(!0)})};var s=function(e){r._beforeUpdate&&r._beforeUpdate(e,r._groups),t.each(r._groups,function(){r._apply(this.elements,this.options)}),r._afterUpdate&&r._afterUpdate(e,r._groups)};r._update=function(n,a){if(a&&"resize"===a.type){var i=t(window).width();if(i===e)return;e=i;
    }n?o===-1&&(o=setTimeout(function(){s(a),o=-1},r._throttle)):s(a)},t(r._applyDataApi);var h=t.fn.on?"on":"bind";t(window)[h]("load",function(t){r._update(!1,t)}),t(window)[h]("resize orientationchange",function(t){r._update(!0,t)})});
/*/g/libs/jquery-match-height/0.7.2/jquery.matchHeight.min.js*/


/* /g/libs/jquery-rowmenu/3.0/rowmenu.min.js */
$.fn.rowMenu=function(f){return this.each(function(){function k(){var d=0,l=a.outerWidth();a.addClass("row-menu-init");m.each(function(){var c=$(this),e=c.outerWidth(!0);d+=e;d+b.moreWidth>=l&&(c.attr("data-append",1),1>a.find("."+b.moreBtnClass).length&&(a.append('<li class="'+b.moreBtnClass+'"><a href="javascript:void(0);">'+b.moreText+'</a><ul class="'+b.moreContainerClass+'"></ul></li>'),a.find("."+b.moreBtnClass).insertBefore(a.find('[data-append="1"]').first())),a.find('[data-append="1"]').appendTo(a.find("."+
b.moreContainerClass)));return d});a.find("li").removeAttr("data-append");a.find("."+b.moreBtnClass).find("ul").parent().each(function(){var c=$(this),e=c.find(">ul");c.parents("ul");var g=!1;c.hover(function(){c.find(">a").addClass("active").removeClass("normal");for(i=a.find("."+b.moreBtnClass).find("ul").length;0<=i;i--)c.parent().find(">li").not(c).find("ul").eq(i).hide();g=!0;e.show();$(document).outerWidth()>$(window).outerWidth()&&c.find(">ul").addClass("row-right-level")},function(){c.find(">a").removeClass("active").addClass("normal");
g=!1;window.setTimeout(function(){g||(e.hide(),c.find(">ul").removeClass("row-right-level"))},b.moreHideTimeout)})})}function n(){var d=a.find(".row-menu-container").html();$(window).off("resize.rowMenu");a.find(".row-menu-btn").remove();a.append(d);a.removeClass("row-menu-init")}var h,a=$(this),m=a.find(">li"),b=$.extend({moreText:"\u0415\u0449\u0435",moreWidth:100,resizeTimeout:10,moreHideTimeout:500,moreBtnClass:"row-menu-btn",moreContainerClass:"row-menu-container"},f);"destroy"!=f&&(k(),$(window).on("resize.rowMenu",
function(){"undefined"!==h&&clearTimeout(h);h=setTimeout(function(){a.find("."+b.moreContainerClass).insertAfter(a.find("."+b.moreBtnClass));a.find("."+b.moreContainerClass+"> li").unwrap();a.find("."+b.moreBtnClass).remove();k()},b.resizeTimeout)}));"destroy"==f&&n()})};
/* /g/libs/jquery-rowmenu/3.0/rowmenu.min.js */